# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aug_protobuf_pb2 as aug__protobuf__pb2


class TransactionAugmentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAugmentData = channel.unary_unary(
                '/aug_protobuf.TransactionAugment/SendAugmentData',
                request_serializer=aug__protobuf__pb2.AugType.SerializeToString,
                response_deserializer=aug__protobuf__pb2.BoolType.FromString,
                )


class TransactionAugmentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAugmentData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionAugmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAugmentData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAugmentData,
                    request_deserializer=aug__protobuf__pb2.AugType.FromString,
                    response_serializer=aug__protobuf__pb2.BoolType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aug_protobuf.TransactionAugment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionAugment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAugmentData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aug_protobuf.TransactionAugment/SendAugmentData',
            aug__protobuf__pb2.AugType.SerializeToString,
            aug__protobuf__pb2.BoolType.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
